## Part 1: Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
attrition_df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [9]:
attrition_df['OverTime'] = attrition_df['OverTime'].apply(lambda x: 1 if x == 'Yes' else 0)
attrition_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64 
 5   Education                 1470 non-null   int64 
 6   EducationField            1470 non-null   object
 7   EnvironmentSatisfaction   1470 non-null   int64 
 8   HourlyRate                1470 non-null   int64 
 9   JobInvolvement            1470 non-null   int64 
 10  JobLevel                  1470 non-null   int64 
 11  JobRole                   1470 non-null   object
 12  JobSatisfaction           1470 non-null   int64 
 13  MaritalStatus             1470 non-null   object
 14  NumCompaniesWorked      

In [6]:
# Create y_df with the Attrition and Department columns
y = attrition_df[['Attrition', 'Department']]
y

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [26]:
y['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [11]:
# Create a list of at least 10 column names to use as X data

X = attrition_df[
    ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime',
     'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany',
     'YearsSinceLastPromotion', 'NumCompaniesWorked']
]

# Create X_df using your selected columns

X_df = X

# Show the data types for X_df

X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Education                1470 non-null   int64
 1   Age                      1470 non-null   int64
 2   DistanceFromHome         1470 non-null   int64
 3   JobSatisfaction          1470 non-null   int64
 4   OverTime                 1470 non-null   int64
 5   StockOptionLevel         1470 non-null   int64
 6   WorkLifeBalance          1470 non-null   int64
 7   YearsAtCompany           1470 non-null   int64
 8   YearsSinceLastPromotion  1470 non-null   int64
 9   NumCompaniesWorked       1470 non-null   int64
dtypes: int64(10)
memory usage: 115.0 KB


In [12]:
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Education                1470 non-null   int64
 1   Age                      1470 non-null   int64
 2   DistanceFromHome         1470 non-null   int64
 3   JobSatisfaction          1470 non-null   int64
 4   OverTime                 1470 non-null   int64
 5   StockOptionLevel         1470 non-null   int64
 6   WorkLifeBalance          1470 non-null   int64
 7   YearsAtCompany           1470 non-null   int64
 8   YearsSinceLastPromotion  1470 non-null   int64
 9   NumCompaniesWorked       1470 non-null   int64
dtypes: int64(10)
memory usage: 115.0 KB


In [13]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,stratify=y)


In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X['OverTime'].value_counts()

OverTime
0    1054
1     416
Name: count, dtype: int64

In [14]:
# Create a StandardScaler

scaler = StandardScaler()

# Fit the StandardScaler to the training data

scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [32]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)



# Fit the encoder to the training data

y_encoded = encoder.fit_transform(y[['Department']])


# Create two new variables by applying the encoder
# to the training and testing data

y_train_encoded = encoder.fit_transform(y_train[['Department']])
y_test_encoded = encoder.transform(y_test[['Department']])

print(y_train_encoded[:5])

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [31]:
# Create a OneHotEncoder for the Attrition column
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data

y_encoded = encoder.fit_transform(y[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data

y_train_encoded_1 = encoder.fit_transform(y_train[['Attrition']])
y_test_encoded_1 = encoder.transform(y_test[['Attrition']])

print(y_train_encoded_1[:5])

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [33]:
# Find the number of columns in the X training data
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

num_features = X_train.shape[1]
# Create the input layer
input_layer = Input(shape=(num_features,))

# Create at least two shared layers
shared_dense1 = Dense(64, activation='relu')
shared_dense2 = Dense(32, activation='relu')

x = shared_dense1(input_layer)
x = shared_dense2(x)

output_layer = Dense(1, activation='sigmoid')(x)

model = Model(inputs=input_layer, outputs=output_layer)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10)]              0         
                                                                 
 dense (Dense)               (None, 64)                704       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2817 (11.00 KB)
Trainable params: 2817 (11.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
# Create a branch for Department
# with a hidden layer and an output layer
num_department_features = y_train_encoded.shape[1]
department_input = Input(shape=(num_department_features,), name='department_input')

# Create the hidden layer
department_hidden = Dense(64, activation='relu')(department_input)

department_output = Dense(10, activation='softmax', name='department_output')(department_hidden)

department_model = Model(inputs=department_input, outputs=department_output)

department_model = Model(inputs=department_input, outputs=department_output)

department_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

department_model.summary()
# Create the output layer



Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 department_input (InputLay  [(None, 3)]               0         
 er)                                                             
                                                                 
 dense_3 (Dense)             (None, 64)                256       
                                                                 
 department_output (Dense)   (None, 10)                650       
                                                                 
Total params: 906 (3.54 KB)
Trainable params: 906 (3.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
# Create a branch for Attrition
# with a hidden layer and an output layer
num_department_features_1 = y_train_encoded_1.shape[1]
department_input_1 = Input(shape=(num_department_features,), name='department_input')

# Create the hidden layer
department_hidden_1 = Dense(64, activation='relu')(department_input_1)

department_output_1 = Dense(10, activation='softmax', name='department_output_1')(department_hidden_1)

department_model_1 = Model(inputs=department_input_1, outputs=department_output_1)

department_model_1 = Model(inputs=department_input_1, outputs=department_output_1)

department_model_1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

department_model_1.summary()

# Create the output layer



Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 department_input (InputLay  [(None, 3)]               0         
 er)                                                             
                                                                 
 dense_4 (Dense)             (None, 64)                256       
                                                                 
 department_output_1 (Dense  (None, 10)                650       
 )                                                               
                                                                 
Total params: 906 (3.54 KB)
Trainable params: 906 (3.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
# Create the model
input_layer = Input(shape=(10,), name='input')

# Compile the model

shared1 = Dense(64, activation='relu', name='shared1')(input_layer)
shared2 = Dense(128, activation='relu', name='shared2')(shared1)

department_hidden = Dense(32, activation='relu', name='department_hidden')(shared2)
department_output = Dense(3, activation='softmax', name='department_output')(department_hidden)

attrition_hidden = Dense(32, activation='relu', name='attrition_hidden')(shared2)
attrition_output = Dense(2, activation='softmax', name='attrition_output')(attrition_hidden)

model = Model(inputs=input_layer, outputs=[department_output, attrition_output], name='model')

model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'categorical_crossentropy'},
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})
# Summarize the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input (InputLayer)          [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input[0][0]']               
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                              

In [42]:
# Train the model

history = model.fit(
    X_train,
    {'department_output': y_train_encoded, 'attrition_output': y_train_encoded_1},
   epochs=100,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/100
28/28 [==============================] - 2s 17ms/step - loss: 1.7878 - department_output_loss: 0.9064 - attrition_output_loss: 0.8814 - department_output_accuracy: 0.6118 - attrition_output_accuracy: 0.7753 - val_loss: 1.3362 - val_department_output_loss: 0.8739 - val_attrition_output_loss: 0.4623 - val_department_output_accuracy: 0.5837 - val_attrition_output_accuracy: 0.8235
Epoch 2/100
28/28 [==============================] - 0s 4ms/step - loss: 1.2021 - department_output_loss: 0.7737 - attrition_output_loss: 0.4284 - department_output_accuracy: 0.6606 - attrition_output_accuracy: 0.8411 - val_loss: 1.3323 - val_department_output_loss: 0.8893 - val_attrition_output_loss: 0.4430 - val_department_output_accuracy: 0.6154 - val_attrition_output_accuracy: 0.8190
Epoch 3/100
28/28 [==============================] - 0s 5ms/step - loss: 1.1853 - department_output_loss: 0.7765 - attrition_output_loss: 0.4089 - department_output_accuracy: 0.6470 - attrition_output_accuracy: 0.8434

In [55]:
# Evaluate the model with the testing data


results = model.evaluate(
    X_test,
    {'department_output': y_test_encoded, 'attrition_output': y_test_encoded_1}
)

# Print results directly as shown in your example output
print("[", end="")
print(f"{results[0]},", end=" ")
print(f"{results[1]},", end=" ")
print(f"{results[2]},", end=" ")
print("]", end="")

12/12 [==============================] - 0s 7ms/step - loss: 1.4122 - department_output_loss: 0.9164 - attrition_output_loss: 0.4958 - department_output_accuracy: 0.6386 - attrition_output_accuracy: 0.8424
[1.4121637344360352, 0.9163530468940735, 0.49581068754196167, ]

In [54]:
# Print the accuracy for both department and attrition
print("Metrics Names:", model.metrics_names)
department_accuracy = results[3]
attrition_accuracy = results[4]
print(f"Department predictions accuracy: {department_accuracy:.4f}")
print(f"Attrition predictions accuracy: {attrition_accuracy:.4f}")

Metrics Names: ['loss', 'department_output_loss', 'attrition_output_loss', 'department_output_accuracy', 'attrition_output_accuracy']
Department predictions accuracy: 0.4958
Attrition predictions accuracy: 0.6386


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Not necessarily. For department predictions, accuracy can be misleading if classes are imbalanced. Precision, recall, and F1-score are better in such cases. For attrition, accuracy is fine if classes are balanced; otherwise, best to use precision and recall.
2. Softmax for department output: Converts logits to probabilities for multi-class classification, ensuring the probabilities sum to one.
Sigmoid for attrition output: Outputs a probability between 0 and 1 for binary classification, indicating the likelihood of attrition.
3. Balance the dataset: Use techniques like SMOTE or adjust class weights.
Feature engineering: Create interaction and domain-specific features.
Hyperparameter tuning: Use grid search or random search to optimize model parameters.
Regularization: Implement dropout and L2 regularization to prevent overfitting.
Cross-validation: Use k-fold cross-validation to ensure robust performance.
Try different architectures: Experiment with more complex neural networks or ensemble methods